dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request OR tag is present

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-wrangler
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [TERRAFORM-AWS-WRANGLER v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-wrangler/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: ZCv557ZNYu3qAZR6VhQvHaiB988CyHeN7AQIfiMW3xsJ9YxAKUXq6OTLSernJQIL5fd0n42mUDQW3sXNR6L6Af3RpmQKImwtDvyZSM29dgyCzMUfbo1C0qogkHL+IGCH/0fbR2PbWMjRb/I/qLnNOTGQC9c0NnJCdAFxkpKoxVhXHSVhNWZwW6tJFJZB0SCMQDJyT/v6qlJKyo4exTmwFWQ2Anj6/AUSms+YpNdqZBnA6PM+wiWysyty+n+CkcqCmUeLEm83vytvzZkny7n672FYmoOitM4OQUWmPVf2cBd/1xRKoYDDkaA6HEepmWSuDP3T1KjBbr7UP+C4K3yRHaAdyOxpuUV463KRhvNQKFe1drXhOrdZWcJfw8zuO7XPmyN2g4bNcCnCqBvWiKD/L7v0bNPk7D9Bh6RmJrVxAi+Q7LKcNS3l2gPkyLAvqxf6KxnQ4xuK8zhhseuy+Yx13gEtJhKD/OkDU1yI3mZRaDZ6KFqDtIkZm3EOUIGOvmz+MV8BJV3TlE1tPS+I41xo2Z95SOc66yZuaN+zwnmgbLCYnn9SDIIgcwG79rnOKOuJgaR9jOWrs4IlV+1B34Ssw3pLooerj+LpspJkAZyuAaTXXA5s43SJ2uZ7CdjcrE3x4T/Aby/rbZGlc95roSGcb9xpP4XkFhPBSNMefPV18Rw=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-wrangler
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
